# Architecture
arch: small_twins_model

# ===== Dataset ===== #
data_url: data_url/imagenet/
set: ImageNet
num_classes: 1000
mix_up: 0.8
cutmix: 1.0
auto_augment: rand-m9-mstd0.5-inc1
interpolation: bicubic
re_prob: 0.25
re_mode: pixel
re_count: 1
mixup_prob: 1.
switch_prob: 0.5
mixup_mode: batch


# ===== Learning Rate Policy ======== #
optimizer: adamw
base_lr: 0.0005
warmup_lr: 0.000001
min_lr: 0.00001
lr_scheduler: cosine_lr
warmup_length: 5
nonlinearity: GELU


# ===== Network training config ===== #
amp_level: O1
accumulation_step: 1
keep_bn_fp32: True
beta: [ 0.9, 0.999 ]
clip_global_norm_value: 5.
is_dynamic_loss_scale: True
epochs: 300
label_smoothing: 0.1
loss_scale: 1024
weight_decay: 0.05
momentum: 0.9
batch_size: 256
crop_pct: 0.875

# ===== Hardware setup ===== #
num_parallel_workers: 12
device_num: 8
device_target: Ascend 

# Ascend
# ===== Model config ===== #
drop_path_rate: 0.2